---
title: "Happingess Rankings Correlation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(ggplot2)
library(readr)
setwd("/Users/jonatanquintana/Downloads")
Happy <- read.csv("2015.csv")
```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A

```{r}
Happy$Continent <- NA

Happy$Continent[which(Happy$Region %in% c("Australia and New Zealand"))] <- "Australia"
Happy$Continent[which(Happy$Region %in% c("North America"))] <- "North America"
Happy$Continent[which(Happy$Region %in% c("Sub-Saharan Africa", "Middle East and Northern Africa"))] <- "Africa"
Happy$Continent[which(Happy$Region %in% c("Western Europe", "Central and Eastern Europe"))] <- "Europe"
Happy$Continent[which(Happy$Region %in% c("Eastern Asia", "Southeastern Asia", "Southern Asia"))] <- "Asia"
Happy$Continent[which(Happy$Region %in% c("Latin America and Caribbean"))] <- "South America"

life <- aggregate(Happy[,2:8], list(Happy$Region), mean)

Happy %>% 
  rename(health.life = Health..Life.Expectancy.) %>% 
  group_by(Continent) %>% 
  summarise("Average_Happiness_Score" = mean(Happiness.Score, 1)) %>% 
  ggplot(aes(x = reorder(Continent, - Average_Happiness_Score), y = Average_Happiness_Score, fill
             = Continent)) + 
  geom_bar(stat = "identity") + 
  geom_text(aes(label = Average_Happiness_Score), vjust = -0.2) +
  theme_classic() +
  theme(axis.text.x = element_text(vjust = .7)) + 
  theme(legend.position = "none") + 
  labs(title = "Average Happiness Rank by Continent",
       subtitle = "Happiness levels >= 7 considered good while levels <= 5 \n considered unhappy",
       x = NULL,
       y = "Score") + 
  scale_fill_manual(values = c("Australia" = "#f4d03f",
                               "North America" = "#f1c40f",
                               "South America" = "#d4ac0d",
                               "Europe" = "#b7950b",
                               "Asia" = "#9a7d0a",
                               "Africa" = "#7d6608"))
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B(Interactive)

```{r}
Health <- life %>% 
  select(Group.1, Happiness.Score, Health..Life.Expectancy.) %>% 
  rename(Health.Life = Health..Life.Expectancy.,
         Region = Group.1) %>% 
  group_by(Region) %>% 
  mutate(Health.Life = round(Health.Life, 2)) %>% 
  mutate(Happiness.Score = round(Happiness.Score, 2))

p <- plot_ly(data = Health,
             x = ~Happiness.Score,
             y = ~Health.Life,
             color = ~Region,
             colors = c(
               "Australia and New Zealand" = "#2e86c1",
               "North America" = "#6c3483",
               "Western Europe" = "#2e4053",
               "Central and Eastern Europe" = "#2e4053",
               "Sub-Saharan Africa" = "#f39c12",
               "Middle East and Northern Africa" = "#f39c12",
               "Eastern Asia" = "#239b56", 
               "Southeastern Asia" = "#239b56",
               "Southern Asia" = "#239b56", 
               "Latin America and Caribbean" = "#a93226"
             ),
             type = 'scatter',
             mode = 'markers',
             text = ~Region) %>% 
  layout(title = 'list'(text = 'Health affect on happiness score by Region',
                        y = 0.97,
                        x = 0.45),
         yaxis = list(title = 'Health Score'),
         xaxis = list(title = 'Happiness Score')) %>% 
  layout(showlegend = FALSE)

p %>%
  config(displayModeBar = FALSE)
```

### Chart C(Interactive)

```{r}
Economy <- life %>% 
  select(Group.1, Happiness.Score, Economy..GDP.per.Capita.) %>% 
  rename(Economy.GDP = Economy..GDP.per.Capita.,
         Region = Group.1) %>% 
  group_by(Region) %>% 
  mutate(Happiness.Score = round(Happiness.Score, 2)) %>% 
  mutate(Economy.GDP = round(Economy.GDP, 2))

P <- plot_ly(data = Economy,
             x = ~Happiness.Score,
             y = ~Economy.GDP,
             color = ~Region,
             colors = c(
                       "Australia and New Zealand" = "#2e86c1",
               "North America" = "#6c3483",
               "Western Europe" = "#2e4053",
               "Central and Eastern Europe" = "#2e4053",
               "Sub-Saharan Africa" = "#f39c12",
               "Middle East and Northern Africa" = "#f39c12",
               "Eastern Asia" = "#239b56", 
               "Southeastern Asia" = "#239b56",
               "Southern Asia" = "#239b56", 
               "Latin America and Caribbean" = "#a93226"
             ),
             type = 'scatter',
             mode = 'markers',
             text = ~Region) %>% 
  layout(title = list(text = 'Economy affect on happiness score by Region',
                      y = 0.97,
                      x = 0.45),
         yaxis = list(title = 'Economy GDP'),
         xaxis = list(title = 'Happiness Score')) %>% 
  layout(showlegend = FALSE)

P %>% 
  config(displayModeBar = FALSE)
```

